version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - cd app
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew test
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app/build/reports/**/*
    
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'